server:
  port: 8081

spring:
  application:
    name: user-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: User Service
    description: User Management Microservice
    version: 1.0.0

