server:
  port: 8083

spring:
  application:
    name: order-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Order Service
    description: Order Management Microservice
    version: 1.0.0

